const A=document.getElementById('app');const S=JSON.parse(localStorage.getItem('im_state')||'null')||{user:null,tab:'login',friends:[],chats:{},history:[]};
const save=()=>localStorage.setItem('im_state',JSON.stringify(S));
const esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function splash(next){A.innerHTML=`<div class="screen splash"><div><div class="logo">IM</div><div class="brand"><h1>Islamic Messenger</h1><p>মুরশিদ • Connect with Ummah</p></div></div></div>`;setTimeout(next,700)}
function auth(){A.innerHTML=`<div class="screen auth"><div class="brand"><div class="logo" style="margin:auto;background:var(--g)">IM</div><h1>Islamic Messenger</h1><p class="muted">নিরাপদ ও সুন্দর মেসেজিং</p></div><div class="tabs"><button class="${S.tab==='login'?'active':''}" onclick="S.tab='login';auth()">লগইন</button><button class="${S.tab==='reg'?'active':''}" onclick="S.tab='reg';auth()">রেজিস্টার</button></div><div id="form"></div></div>`;let f=document.getElementById('form');if(S.tab==='reg')f.innerHTML=`<div class="field"><label>দেশ</label><select id="country"><option value="+880">বাংলাদেশ (+880)</option><option value="+91">ভারত (+91)</option><option value="+92">পাকিস্তান (+92)</option><option value="+966">সৌদি আরব (+966)</option><option value="+971">UAE (+971)</option><option value="+1">USA/Canada (+1)</option></select></div><div class="field"><label>First name</label><input id="fn"></div><div class="field"><label>Last name</label><input id="ln"></div><div class="field"><label>মোবাইল নম্বর</label><input id="phone" inputmode="tel"></div><div class="field"><label>৪ সংখ্যার Friend Code</label><input id="code" maxlength="4" inputmode="numeric"></div><button class="primary" onclick="register()">রেজিস্টার করুন</button>`;else f.innerHTML=`<div class="field"><label>কান্ট্রি কোড</label><select id="lc"><option>+880</option><option>+91</option><option>+92</option><option>+966</option><option>+971</option><option>+1</option></select></div><div class="field"><label>মোবাইল নম্বর</label><input id="lp" inputmode="tel"></div><div class="field"><label>৪ সংখ্যার Friend Code</label><input id="lcode" maxlength="4" inputmode="numeric"></div><button class="primary" onclick="login()">লগইন</button>`}
function register(){let phone=document.getElementById('phone').value.trim(),code=document.getElementById('code').value.trim();if(!/\d{4}/.test(code)||!phone)return alert('তথ্যগুলো ঠিকভাবে দিন');if(S.user&&S.user.phone===phone)return alert('এই নম্বরে ইতিমধ্যে অ্যাকাউন্ট আছে');S.user={name:(document.getElementById('fn').value+' '+document.getElementById('ln').value).trim()||'User',phone,code,avatar:'IM'};save();home()}
function login(){let p=document.getElementById('lp').value.trim(),c=document.getElementById('lcode').value.trim();if(!S.user||S.user.phone!==p||S.user.code!==c)return alert('নম্বর বা Friend Code মিলেনি');home()}
function home(){A.innerHTML=`<div class="screen home"><div class="top"><div class="toprow"><div><div class="muted" style="color:#c9dfd9">স্বাগতম</div><h2 style="margin:2px 0">${esc(S.user?.name||'User')}</h2></div><button class="avatar" onclick="profile()">${esc(S.user?.avatar||'IM')}</button></div></div><div class="section"><div class="card"><b>Friend Code দিয়ে বন্ধু যোগ করুন</b><div class="add" style="margin-top:9px"><input id="fc" placeholder="৪ সংখ্যার কোড"><button class="iconbtn" onclick="addFriend()">Add</button></div></div><div class="card"><b>Friends</b><div id="friends"></div></div><div class="card"><div class="brand"><div class="logo" style="margin:auto;width:65px;height:65px;font-size:25px;background:var(--g)">IM</div><b>AF-এর মালিক — হাফেজ মোহাম্মদ বাইজিদ</b><div class="muted">যোগাযোগের জন্য প্রোফাইল থেকে তথ্য দিন</div></div></div></div><div class="bottom"><button onclick="home()">Home</button><button onclick="profile()">Profile</button><button onclick="settings()">Settings</button></div></div>`;let el=document.getElementById('friends');if(!S.friends.length)el.innerHTML='<p class="muted">এখনও কোনো বন্ধু নেই।</p>';S.friends.forEach((x,i)=>{el.innerHTML+=`<div class="friend" onclick="chat(${i})"><div class="avatar" style="width:42px;height:42px">${esc(x.name[0]||'F')}</div><div style="flex:1"><b>${esc(x.name)}</b><div class="muted">FC: ${esc(x.code)} ${x.online?'<span class="online"></span>':''}</div></div></div>`})}
function addFriend(){let c=document.getElementById('fc').value.trim();if(!/\d{4}/.test(c))return alert('৪ সংখ্যার কোড দিন');if(S.friends.some(x=>x.code===c))return alert('বন্ধু আগে থেকেই আছে');S.friends.push({name:'Friend '+c,code:c,online:false,blocked:false});save();home()}
function chat(i){let f=S.friends[i];let key=f.code;S.chats[key]??=[];A.innerHTML=`<div class="screen chat"><div class="chathead"><button onclick="home()">‹</button><div class="avatar" style="width:40px;height:40px">${esc(f.name[0])}</div><div><b>${esc(f.name)}</b><div class="muted" style="color:#d6e5e1">${f.online?'Online':'Offline'}</div></div><div class="actions"><button onclick="alert('Audio call demo')">☎</button><button onclick="alert('Video call demo')">▣</button><button onclick="menu(${i})">⋮</button></div></div><div class="messages" id="msgs"></div><div class="composer"><input id="msg" placeholder="মেসেজ লিখুন..." onkeydown="if(event.key==='Enter')send(${i})"><button class="iconbtn" onclick="send(${i})">➤</button></div></div>`;renderMsgs(key,i)}
function renderMsgs(key,i){let m=document.getElementById('msgs');m.innerHTML='';S.chats[key].forEach((x,n)=>m.innerHTML+=`<div class="bubble ${x.mine?'mine':''}" onclick="delMenu(${i},${n})">${esc(x.text)} <small>${x.mine?' ✓✓':''}</small></div>`);m.scrollTop=m.scrollHeight}
function send(i){let input=document.getElementById('msg'),t=input.value.trim();if(!t)return;let k=S.friends[i].code;S.chats[k].push({text:t,mine:true,ts:Date.now()});save();input.value='';renderMsgs(k,i)}
function menu(i){let f=S.friends[i];if(confirm(f.blocked?'Unblock করবেন?':'Block করবেন?')){f.blocked=!f.blocked;save();chat(i)}}
function delMenu(i,n){let k=S.friends[i].code;let q=confirm('OK = শুধু আমার জন্য ডিলিট\nCancel = বাতিল');if(q){S.chats[k].splice(n,1);save();renderMsgs(k,i)}}
function profile(){A.innerHTML=`<div class="screen auth"><button onclick="home()">← Home</button><h2>Profile</h2><div class="card"><div class="avatar" style="margin:auto;width:80px;height:80px">${esc(S.user.avatar)}</div><h3 style="text-align:center">${esc(S.user.name)}</h3><p>Phone: ${esc(S.user.phone)}</p><p>Friend Code: <b>${esc(S.user.code)}</b></p><button class="primary" onclick="alert('Profile update demo')">Profile Update</button></div><div class="card"><b>History</b><p class="muted">History ৭২ ঘণ্টা পরে স্বয়ংক্রিয়ভাবে মুছে যাবে।</p></div></div>`}
function settings(){A.innerHTML=`<div class="screen auth settings"><button onclick="home()">← Home</button><h2>Settings</h2><div class="card">${['Account','Privacy','Security','Notifications','Chats','Theme','Data and Storage','Blocked Friends','Language','Account Switch','Help','About Islamic Messenger'].map(x=>`<div class="setting"><span>${x}</span><span>›</span></div>`).join('')}<div class="setting" onclick="logout()"><b style="color:#b33">Logout</b><span>›</span></div></div></div>`}
function logout(){S.user=null;save();S.tab='login';auth()}
if(S.user)splash(home);else splash(auth);
