const express=require('express');const http=require('http');const path=require('path');const crypto=require('crypto');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const multer=require('multer');const {Pool}=require('pg');const {Server}=require('socket.io');
const app=express(),server=http.createServer(app);const PORT=Number(process.env.PORT||10000),JWT_SECRET=process.env.JWT_SECRET||'CHANGE_ME_IN_RENDER',DATABASE_URL=process.env.DATABASE_URL||'';
const io=new Server(server,{cors:{origin:true,credentials:true}});app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:50*1024*1024}});app.use(express.static(__dirname,{index:false}));
const pool=DATABASE_URL?new Pool({connectionString:DATABASE_URL,ssl:DATABASE_URL.includes('localhost')?false:{rejectUnauthorized:false}}):null;
async function query(t,p=[]){if(!pool){const e=new Error('DATABASE_URL is not configured');e.statusCode=503;throw e}return pool.query(t,p)}
async function initDb(){if(!pool)return;await query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,name TEXT NOT NULL,country TEXT NOT NULL,phone TEXT UNIQUE NOT NULL,pin_hash TEXT NOT NULL,code TEXT UNIQUE NOT NULL,avatar_url TEXT,created_at TIMESTAMPTZ DEFAULT now())`);await query(`CREATE TABLE IF NOT EXISTS media_files(id TEXT PRIMARY KEY,owner_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,mime TEXT NOT NULL,original_name TEXT,data BYTEA NOT NULL,created_at TIMESTAMPTZ DEFAULT now())`);await query(`CREATE TABLE IF NOT EXISTS friendships(user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,friend_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ DEFAULT now(),PRIMARY KEY(user_id,friend_id))`);await query(`CREATE TABLE IF NOT EXISTS blocks(user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,blocked_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(user_id,blocked_id))`);await query(`CREATE TABLE IF NOT EXISTS messages(id BIGSERIAL PRIMARY KEY,sender_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,receiver_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL DEFAULT 'text',body TEXT,media_url TEXT,seen BOOLEAN DEFAULT false,created_at TIMESTAMPTZ DEFAULT now())`);await query(`CREATE TABLE IF NOT EXISTS stories(id BIGSERIAL PRIMARY KEY,user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,type TEXT NOT NULL,body TEXT,media_url TEXT,created_at TIMESTAMPTZ DEFAULT now(),expires_at TIMESTAMPTZ NOT NULL)`)}
function pubUser(u){return{id:u.id,name:u.name,country:u.country,phone:u.phone,code:u.code,avatarUrl:u.avatar_url||''}}function token(u){return jwt.sign({id:u.id,code:u.code},JWT_SECRET,{expiresIn:'30d'})}function pubMsg(m){return{id:m.id,senderId:m.sender_id,receiverId:m.receiver_id,type:m.type,body:m.body||'',mediaUrl:m.media_url||'',seen:!!m.seen,createdAt:m.created_at,senderName:m.sender_name||'',senderCode:m.sender_code||''}}
async function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'লগইন প্রয়োজন'});const d=jwt.verify(h.slice(7),JWT_SECRET);const r=await query('SELECT id,name,country,phone,code,avatar_url FROM users WHERE id=$1',[d.id]);if(!r.rowCount)return res.status(401).json({error:'অ্যাকাউন্ট পাওয়া যায়নি'});req.user=r.rows[0];next()}catch(e){res.status(401).json({error:'লগইন সেশন অবৈধ'})}}
async function byCode(c){const r=await query('SELECT id,name,country,phone,code,avatar_url FROM users WHERE code=$1',[String(c||'').trim()]);return r.rows[0]||null}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'BD Islamic Messenger',databaseConfigured:!!DATABASE_URL}));
app.post('/api/register',async(req,res)=>{try{const name=String(req.body.name||'').trim(),country=String(req.body.country||'+880').trim(),phone=String(req.body.phone||'').replace(/\s+/g,''),pin=String(req.body.pin||'').trim();if(!name||!phone||!/^[0-9]{4}$/.test(pin))return res.status(400).json({error:'নাম, ফোন নম্বর ও ৪ সংখ্যার Secret Code দিন'});const ex=await query('SELECT id FROM users WHERE phone=$1 OR code=$2',[phone,pin]);if(ex.rowCount)return res.status(409).json({error:'এই ফোন নম্বর অথবা Secret Code আগে থেকেই ব্যবহার করা হয়েছে'});const h=await bcrypt.hash(pin,10);const r=await query('INSERT INTO users(name,country,phone,pin_hash,code) VALUES($1,$2,$3,$4,$5) RETURNING *',[name,country,phone,h,pin]);res.json({ok:true,user:pubUser(r.rows[0]),message:'রেজিস্ট্রেশন সফল। এখন Login করুন।'})}catch(e){console.error(e);res.status(500).json({error:'রেজিস্ট্রেশন ব্যর্থ হয়েছে'})}});
app.post('/api/login',async(req,res)=>{try{const phone=String(req.body.phone||'').replace(/\s+/g,''),pin=String(req.body.pin||'').trim();const r=await query('SELECT * FROM users WHERE phone=$1',[phone]);if(!r.rowCount||!(await bcrypt.compare(pin,r.rows[0].pin_hash)))return res.status(401).json({error:'ফোন নম্বর বা Secret Code ভুল'});res.json({ok:true,token:token(r.rows[0]),user:pubUser(r.rows[0])})}catch(e){res.status(500).json({error:'লগইন ব্যর্থ হয়েছে'})}});
app.get('/api/me',auth,(req,res)=>res.json(pubUser(req.user)));
app.get('/api/friends',auth,async(req,res)=>{const r=await query(`SELECT u.*,EXISTS(SELECT 1 FROM messages m WHERE m.sender_id=u.id AND m.receiver_id=$1 AND m.seen=false) unread FROM users u JOIN friendships f ON f.friend_id=u.id WHERE f.user_id=$1 ORDER BY u.name`,[req.user.id]);const online=new Set([...io.sockets.sockets.values()].filter(s=>s.userId).map(s=>s.userId));res.json(r.rows.map(u=>({...pubUser(u),unread:!!u.unread,online:online.has(u.id)})))});
app.get('/api/users/by-code/:code',auth,async(req,res)=>{const u=await byCode(req.params.code);if(!u)return res.status(404).json({error:'User Code পাওয়া যায়নি'});if(u.id===req.user.id)return res.status(400).json({error:'নিজেকে বন্ধু করা যাবে না'});res.json(pubUser(u))});
app.post('/api/friends/add',auth,async(req,res)=>{try{const f=await byCode(req.body.code);if(!f)return res.status(404).json({error:'User Code পাওয়া যায়নি'});if(f.id===req.user.id)return res.status(400).json({error:'নিজেকে বন্ধু করা যাবে না'});const b=await query('SELECT 1 FROM blocks WHERE (user_id=$1 AND blocked_id=$2) OR (user_id=$2 AND blocked_id=$1)',[req.user.id,f.id]);if(b.rowCount)return res.status(403).json({error:'এই ব্যবহারকারী Block করা আছে'});await query('INSERT INTO friendships(user_id,friend_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,f.id]);await query('INSERT INTO friendships(user_id,friend_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[f.id,req.user.id]);res.json({ok:true,user:pubUser(f),message:'বন্ধু যোগ হয়েছে'})}catch(e){res.status(500).json({error:'Friend যোগ করা যায়নি'})}});
async function friends(a,b){const r=await query('SELECT 1 FROM friendships WHERE user_id=$1 AND friend_id=$2',[a,b]);return !!r.rowCount}async function blocked(a,b){const r=await query('SELECT 1 FROM blocks WHERE user_id=$1 AND blocked_id=$2',[a,b]);return !!r.rowCount}
app.get('/api/chats/:code/messages',auth,async(req,res)=>{const f=await byCode(req.params.code);if(!f)return res.status(404).json({error:'User পাওয়া যায়নি'});const r=await query(`SELECT m.*,u.name sender_name,u.code sender_code FROM messages m JOIN users u ON u.id=m.sender_id WHERE (m.sender_id=$1 AND m.receiver_id=$2) OR (m.sender_id=$2 AND m.receiver_id=$1) ORDER BY m.created_at ASC`,[req.user.id,f.id]);await query('UPDATE messages SET seen=true WHERE sender_id=$1 AND receiver_id=$2',[f.id,req.user.id]);res.json(r.rows.map(pubMsg))});
app.post('/api/chats/:code/messages',auth,async(req,res)=>{try{const f=await byCode(req.params.code);if(!f)return res.status(404).json({error:'User পাওয়া যায়নি'});if(!(await friends(req.user.id,f.id)))return res.status(403).json({error:'আগে Friend যোগ করুন'});if(await blocked(req.user.id,f.id)||await blocked(f.id,req.user.id))return res.status(403).json({error:'এই চ্যাটটি Block করা আছে'});const type=String(req.body.type||'text'),body=String(req.body.body||''),mediaUrl=req.body.mediaUrl?String(req.body.mediaUrl):null;if(!['text','image','video','audio','file'].includes(type))return res.status(400).json({error:'অবৈধ মেসেজ টাইপ'});if(type==='text'&&!body.trim()||type!=='text'&&!mediaUrl)return res.status(400).json({error:'মেসেজ খালি'});const r=await query('INSERT INTO messages(sender_id,receiver_id,type,body,media_url) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.user.id,f.id,type,body,mediaUrl]);const out=pubMsg({...r.rows[0],sender_name:req.user.name,sender_code:req.user.code});for(const s of io.sockets.sockets.values()){if(s.userId===f.id)s.emit('message:new',out);if(s.userId===req.user.id)s.emit('message:sent',out)}res.json(out)}catch(e){console.error(e);res.status(500).json({error:'মেসেজ পাঠানো যায়নি'})}});
app.post('/api/upload',auth,upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'ফাইল পাওয়া যায়নি'});const mime=req.file.mimetype||'';const type=mime.startsWith('image/')?'image':mime.startsWith('video/')?'video':mime.startsWith('audio/')?'audio':'file';if(type==='file'&&mime!=='application/pdf'&&!mime.startsWith('text/'))return res.status(400).json({error:'এই ফাইল টাইপ এখনো সমর্থিত নয়'});const id=crypto.randomBytes(24).toString('hex');await query('INSERT INTO media_files(id,owner_id,mime,original_name,data) VALUES($1,$2,$3,$4,$5)',[id,req.user.id,mime,req.file.originalname||'',req.file.buffer]);res.json({ok:true,type,url:'/api/media/'+id,name:req.file.originalname||''})}catch(e){console.error(e);res.status(500).json({error:'ফাইল আপলোড ব্যর্থ হয়েছে'})}});
app.get('/api/media/:id',async(req,res)=>{try{const r=await query('SELECT mime,original_name,data FROM media_files WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).end();const m=r.rows[0];res.setHeader('Content-Type',m.mime);res.setHeader('Content-Length',m.data.length);res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(m.original_name||'media')}`);res.end(m.data)}catch(e){res.status(500).end()}});
app.put('/api/profile',auth,async(req,res)=>{try{const name=String(req.body.name||req.user.name).trim(),avatar=String(req.body.avatarUrl||req.user.avatar_url||'');const r=await query('UPDATE users SET name=$1,avatar_url=$2 WHERE id=$3 RETURNING *',[name,avatar||null,req.user.id]);res.json(pubUser(r.rows[0]))}catch(e){res.status(500).json({error:'প্রোফাইল আপডেট করা যায়নি'})}});
app.post('/api/block/:code',auth,async(req,res)=>{const t=await byCode(req.params.code);if(!t)return res.status(404).json({error:'User পাওয়া যায়নি'});await query('INSERT INTO blocks(user_id,blocked_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[req.user.id,t.id]);res.json({ok:true})});app.delete('/api/block/:code',auth,async(req,res)=>{const t=await byCode(req.params.code);if(!t)return res.status(404).json({error:'User পাওয়া যায়নি'});await query('DELETE FROM blocks WHERE user_id=$1 AND blocked_id=$2',[req.user.id,t.id]);res.json({ok:true})});
app.post('/api/stories',auth,async(req,res)=>{try{const type=String(req.body.type||'text'),body=String(req.body.body||''),url=String(req.body.mediaUrl||'');if(!['text','image','video'].includes(type))return res.status(400).json({error:'অবৈধ Story'});if(type==='text'&&!body.trim()||type!=='text'&&!url)return res.status(400).json({error:'Story খালি'});const r=await query('INSERT INTO stories(user_id,type,body,media_url,expires_at) VALUES($1,$2,$3,$4,now()+interval \'72 hours\') RETURNING *',[req.user.id,type,body,url||null]);res.json({ok:true,story:r.rows[0]})}catch(e){res.status(500).json({error:'Story যোগ করা যায়নি'})}});app.get('/api/stories',auth,async(req,res)=>{await query('DELETE FROM stories WHERE expires_at<=now()');const r=await query(`SELECT s.*,u.name,u.code,u.avatar_url FROM stories s JOIN users u ON u.id=s.user_id WHERE s.user_id=$1 OR EXISTS(SELECT 1 FROM friendships f WHERE f.user_id=$1 AND f.friend_id=s.user_id) ORDER BY s.created_at DESC`,[req.user.id]);res.json(r.rows)});
io.use((s,n)=>{try{const t=s.handshake.auth&&s.handshake.auth.token;const d=jwt.verify(t,JWT_SECRET);s.userId=Number(d.id);n()}catch(e){n(new Error('unauthorized'))}});io.on('connection',s=>{s.broadcast.emit('presence',{userId:s.userId,online:true});s.on('call:offer',d=>io.sockets.sockets.forEach(x=>{if(x.userId===Number(d.to))x.emit('call:offer',{from:s.userId,offer:d.offer})}));s.on('call:answer',d=>io.sockets.sockets.forEach(x=>{if(x.userId===Number(d.to))x.emit('call:answer',{from:s.userId,answer:d.answer})}));s.on('call:ice',d=>io.sockets.sockets.forEach(x=>{if(x.userId===Number(d.to))x.emit('call:ice',{from:s.userId,candidate:d.candidate})}));s.on('call:end',d=>io.sockets.sockets.forEach(x=>{if(x.userId===Number(d.to))x.emit('call:end',{from:s.userId})}));s.on('disconnect',()=>s.broadcast.emit('presence',{userId:s.userId,online:false}))});
app.get('/',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));app.use((req,res)=>req.path.startsWith('/api/')?res.status(404).json({error:'Not found'}):res.sendFile(path.join(__dirname,'index.html')));
initDb().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('BD Islamic Messenger on '+PORT))).catch(e=>{console.error(e);server.listen(PORT,'0.0.0.0',()=>console.log('BD Islamic Messenger without DB'))});
